# Generated by Django 4.2.14 on 2024-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.TextField(default='Sin categoria', max_length=55),
        ),
    ]
