# Generated by Django 4.2.14 on 2024-07-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
